pub mod ast;
pub mod builtins;
pub mod bytecode;
pub mod cli;
pub mod error;
pub mod lexer;
pub mod parser;
pub mod token;
pub mod types;
pub mod value;
pub mod vm;
pub mod span;
pub mod pocket;
pub mod state;
pub mod ai_runtime;
pub mod type_checker;
// pub mod llm_interface;
// pub mod sigg_gnn;
// pub mod code_generator;
// pub mod file_operations;
// pub mod self_modify;
// pub mod ai_assistant;
// pub mod autonomous_ai;
// pub mod voice_text_interface;
// pub mod sigg_theory_integrated_ai;
// pub mod sigg_ai_main;
pub mod unified_ai_core;

pub mod server;
